### ISSUE TITLE
Ошибка при скачивании курса

### ISSUE THREAD

**Issue by crazzy-bunny** [limitedeternity/foxford_courses#16]
Ошибка при попытке скачивания курса:
![error](https://user-images.githubusercontent.com/44054649/46794597-d803b700-cd50-11e8-90dd-68f8ada3e830.png)
===========================
 √ Setting up env
 √ Performing startup checks
 √ Instantiating Chromium
 √ Setting up page
 √ Logging in with provided credentials
 √ Aquiring access token
 \ Creating download task list
   → https://foxford.ru/groups/XXXXX
   Downloading
(node:12236) UnhandledPromiseRejectionWarning: Error: Resource unavailable.  Err
or: null; Status: 404.
    at Request.module.exports.checkAvailability.request [as _callback] (C:\snaps
hot\video\out\utils.js:37:25)
    at Request.init.self.callback (C:\snapshot\video\node_modules\request\reques
t.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (C:\snapshot\video\node_modules\request\request.js:11
61:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (C:\snapshot\video\node_modules\request\reque
st.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
 √ Setting up env
 √ Performing startup checks
 √ Instantiating Chromium
 √ Setting up page
 √ Logging in with provided credentials
 √ Aquiring access token
 \ Creating download task list
   → https://foxford.ru/groups/XXXXX
   Downloading
===========================

Далее программа висит бесконечно. Скачивая не происходит.
Содержимое файла links.txt (1 курс, цифры скрыл):
https://foxford.ru/groups/XXXXX

Пробовал запускать и от имени Администратора - никакого эффекта.

Система:
Windows 8.1 x64

**Comment by limitedeternity** [comment]
Я посмотрю, что можно сделать, если будет время.

**Comment by limitedeternity** [comment]
@crazzy-bunny Готово.

**Comment by crazzy-bunny** [comment]
Спасибо большое! Все скачалось)
